#ifndef COLLISION_DETECTOR_CONFIG_H
#define COLLISION_DETECTOR_CONFIG_H

#define COLLISION_DETECTOR_XSHUT_GPIO_CLK_ENABLE() (RCC->IOPENR |= (1U << 0U))
#define COLLISION_DETECTOR_I2C_GPIO_CLK_ENABLE()   (RCC->IOPENR |= (1U << 1U))

#define COLLISION_DETECTOR_XSHUT_GPIO_PORT GPIOA
#define COLLISION_DETECTOR_XSHUT_GPIO_PIN  (1U << 7U)

#define COLLISION_DETECTOR_I2C_ADDRESS 0x52U
#define COLLISION_DETECTOR_I2C_TIMINGR 0x70420f13UL

#define COLLISION_DETECTOR_OBSTACLE_THRESHOLD_MM 100U
#define COLLISION_DETECTOR_RESET_DELAY_MS 5U
#define COLLISION_DETECTOR_BOOT_DELAY_MS 10U

#endif
